services:
  mootd:
    container_name: mootd
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mootd:/srv
#    environment:
#      - TZ=UTC
#      - RENEWAL_TIME=24:00:00
#      - CHANCE=10

volumes:
  mootd: